language: minimal
sudo: required
services:
  - docker
env:
  global:
  - secure: EeTSWmph8CuIgQkOoHrYxLeyJXX5tmw0xXBEV0iHgCHbqyDeAjd6oVjPsdYsntxnxWuNFPqdR/JNu4R/jD4lLwTBw4ZtmQCYSpB7jO2aV9VCW6HBsgV3qbzN8V4V4bM1DbITMYr3JSUGL4xKgw8MjvJDRHf81PQpxqlUHSCxmI1JP1FFTCrPfBwIW0Jyu2iZot3plEWlg0wA37XnSY8x4ncAawNW2Gj1WTkkUTl6kOGo81lkqPH6Gradpwbkl/Ft9m0iul0Rts0vEC8K6buCEX7i2m3cbBcZrJljqD0zwkTYdG5r64T7KYVB0ueH5nGy33WjUM4443F3vYAfLFiLNrYDTnvthr1mLl3vFF5mEWWkJYoqQhO9W8DryuW2Xif5HfHKAHU+S/Gc8eTF32r4Pu/UETdswnbdufx6shn3rDZL3Pu6XmL9gztVDuWne0onXX1EHVWmsIu+FdvXiblJ4GBhSzSjSeM/gSHFMYsjqx0lXPXtuyzyy+uenPq9ezwEcJVxvm6ongU58qcXOcHoy4WXAlXbENUQVD7l0obpHA1dF15fggrqZxxxm7hbJ8cdLsIhlT5o47B28vIgrLdGBfLkJPZKKG+cGQ5Ge7Gn/Bm1XHnHGUW1k80bUd1ufYPZQ+XhmIb+663Bgv5thc55cbKWHSUIdBkyDVmo4v57Dlw=
  - secure: i3VU44Qc7okTRa5cXv2rvcy4BbDSw8QzDo2qpc41WIQsTO5VQmqA5y0YW9kqordvA4qNBoRO/Dhfe4iEf6l+/6vBL4UP0OzXjValA1FnUBunvH7lz6gMWETI3BjkrX9zLsAsaESCOnxK0B3uNAJCZCq461Wa6zTKm1Q5WdlrI0/8thP0BCpDABvLQb6W2CT45b1AKQN1Vam9SDDaQz/B33c7tt1fI/ayqihXiBaW1yCEGlt8IJ2r0uZxCPjo8KDHI938drirppO+6UOfjrXxhBZ/L8bMMghIEngcRqQx2lx/N2Ux+9bjQOmQDxXzn+BMYFLuB9IVpnqsTiGoJxuUE80IcvrhMWY+LnLS7a8jZLFzCykmkdspcfOyJvssk4/y/LrQD4pHtCXTbAvLGffioQzQwovn5hvwk8Tuz/LOlN/ABk5EMIU5pDCA/qcb5L8VFvgHmr6EWTSOjYIpHzPoyT55dKoOPSHcIR5G3boMOdyS4usn27g3ZFjqg4EFU7LUHWXzuzp61Bw/Bsaxc/VVqkZjztWSdZK5qHXbrkJjyGKKbOW8dqCJnhqVmYgSsRn2t80vT3vyV4bFGGWGBxmpmNGPK5M90/rzZGV0pQE49j2Sy4+UVqlZ93tcspphPmoeoD/hGSbzVaCveABjyL75PRtftWW0yZeRJSOx6DT21ao=
script: make build test
deploy:
  - provider: script
    script: "$TRAVIS_BUILD_DIR/build/latest.sh"
    on:
      branch: master
      repo: appstersio/krates-haproxy